#!/bin/bash
# vsys initscript
# Author: sapanb

backend="/vsys"

case "$1" in
    start)
        echo -n "Starting vsys:"
        if [ ! -d $backend ]; then mkdir $backend; fi
        find /vservers -maxdepth 1 -type d | perl -e 'while (<>) {if (/(\/vservers\/(.*_.*))/) {$dir=$1;if (not (-d "$dir/vsys")) {mkdir "$dir/vsys";}}}'
        frontends=`find /vservers -maxdepth 1 -type d | perl -e 'while (<>) {if (/(\/vservers\/(.*_.*))/) {$dir=$1;$slice=$2;printf "-frontend $dir/vsys $slice "}}'`
        vsys_command="/usr/bin/vsys -backend $backend $frontends"
        echo $vsys_command
        $vsys_command
        ;;
    stop)
        echo -n "Stopping $prog:"
        killall vsys
        exit 0
        ;;
    *)
        echo $"Usage: $0 {start|stop}"
        exit 1
        ;;
esac

# Source function library.
. /etc/rc.d/init.d/functions
